from functools import reduce 

'''
#Asignment#
Complete the lines_with_sequence function. It should return a series of curried functions

The "sequence" is generated by the first with_char that has been provided for you.

You need to define and return a second curried function. I called mine with_length. 
It should accept the final parameter, a doc string, and return the number of lines 
that contain the sequence.

1. Define the with_length function inside the with_char function, it should accept a doc.
2. Split the doc into lines.
3. Use a loop (or if you're feeling fancy, import and use reduce) to count the number of lines that contain the sequence in them.
4. Return the count from the with_length function.
5. Return the with_length function from the with_char function.
'''

def lines_with_sequence(char: str):
    def with_char(len: int):
        sequence: str = char * len
        def with_len(doc):
            lines: list[str] = doc.split("\n")
            result = reduce(lambda acc, line: acc + int(sequence in line), lines, 0)
            return result

            # result = list(filter(lambda line: sequence in line, lines))
            # count = len(result)

            # count = 0
            # for line in lines:
            #     if sequence in line:
            #         count += 1
            # return count
        
        return with_len
    return with_char


run_cases = [
    (
        "#",
        3,
        """###
@##
$$$
###""",
        2,
    ),
    (
        "$",
        2,
        """$$$
$
***
@@@
$$
$$$""",
        3,
    ),
]

submit_cases = run_cases + [
    ("%", 1, "", 0),
    (
        "*",
        3,
        """***
*
$$$$$$
xxx
****
***
***""",
        4,
    ),
]

def test(char, length, doc, expected_output):
    print("---------------------------------")
    print(f"Input char: {char}")
    print(f"Input length: {length}")
    print("Input doc:")
    print(doc)
    print(f"Expected: {expected_output}")
    num_lines = lines_with_sequence(char)(length)(doc)
    print(f"Actual:   {num_lines}")
    if num_lines == expected_output:
        print("Pass")
        return True
    print("Fail")
    return False